### PR TITLE
Fix bug: User was not able to update details without providing password

### PR DESCRIPTION
**Pull request by vikrant-pune**
Current code was raising error, When user was trying to update name / other details from UI
`backend_1       |   File "./app/crud/crud_user.py", line 34, in update
backend_1       |     if update_data["password"]:
backend_1       | KeyError: 'password'
`

### CODE REVIEW

**Comment by vikrant-pune** [comment]
@tiangolo Could you review / merge this

**Comment by luisliz** [comment]
This should be merged asap

**Review by lsglucas — APPROVED** [review]

**Comment by osouza-de** [comment]
Nice solution, but unfortunately it's duplicated: #346

**Comment by tiangolo** [comment]
Thank you! Good catch @vikrant-pune :nerd_face: 

This was solved in another PR, so I'll now close this one. :coffee:

**Pull request closed without merging**
