### PR TITLE
It works now (upd dependencies and fix crud_user )

### PR DESCRIPTION
**Pull request by da-maltsev**
Here I updated some dependencies to make this project able to up. 
Also fixed crud_user to make update without password possible.

### CODE REVIEW

**Comment by da-maltsev** [comment]
added a big commit with changes from https://github.com/pyb4430/full-stack-fastapi-postgresql

**Comment by saffist3r** [comment]
Please merge this branch, everything is set up with no warnings, we can start from @da-maltsev work in order to maintain it.

**Comment by simonbogarde** [comment]
Hi @da-maltsev, thanks a lot for your fixes and updates. I tried for hours to get the original template running.

**Comment by scharfm16** [comment]
@da-maltsev Hey tysm for updating this! I seem to be getting issue on backend python 3.10 dependencies. Not sure if there were breaking changes to python since this pr.

Full Stack trace: 
```
2023-04-09 14:48:38 Checking for script in /app/prestart.sh
2023-04-09 14:48:38 Running script /app/prestart.sh
2023-04-09 14:48:39 Traceback (most recent call last):
2023-04-09 14:48:39   File "/app/app/backend_pre_start.py", line 6, in <module>
2023-04-09 14:48:39     from app.db.session import SessionLocal
2023-04-09 14:48:39   File "/app/app/db/session.py", line 7, in <module>
2023-04-09 14:48:39     from app.core.config import settings
2023-04-09 14:48:39   File "/app/app/core/config.py", line 11, in <module>
2023-04-09 14:48:39     class Settings(BaseSettings):
2023-04-09 14:48:39   File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
2023-04-09 14:48:39   File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
2023-04-09 14:48:39   File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
2023-04-09 14:48:39   File "pydantic/fields.py", line 557, in pydantic.fields.ModelField.prepare
2023-04-09 14:48:39   File "pydantic/fields.py", line 831, in pydantic.fields.ModelField.populate_validators
2023-04-09 14:48:39   File "pydantic/networks.py", line 591, in __get_validators__
2023-04-09 14:48:39   File "pydantic/networks.py", line 578, in pydantic.networks.import_email_validator
2023-04-09 14:48:39   File "/usr/local/lib/python3.7/site-packages/email_validator/__init__.py", line 6, in <module>
2023-04-09 14:48:39     import dns.resolver
2023-04-09 14:48:39   File "/usr/local/lib/python3.7/site-packages/dns/resolver.py", line 39, in <module>
2023-04-09 14:48:39     import dns.query
2023-04-09 14:48:39   File "/usr/local/lib/python3.7/site-packages/dns/query.py", line 58, in <module>
2023-04-09 14:48:39     import httpx
2023-04-09 14:48:39   File "/usr/local/lib/python3.7/site-packages/httpx/__init__.py", line 2, in <module>
2023-04-09 14:48:39     from ._api import delete, get, head, options, patch, post, put, request, stream
2023-04-09 14:48:39   File "/usr/local/lib/python3.7/site-packages/httpx/_api.py", line 4, in <module>
2023-04-09 14:48:39     from ._client import Client
2023-04-09 14:48:39   File "/usr/local/lib/python3.7/site-packages/httpx/_client.py", line 29, in <module>
2023-04-09 14:48:39     from ._transports.default import AsyncHTTPTransport, HTTPTransport
2023-04-09 14:48:39   File "/usr/local/lib/python3.7/site-packages/httpx/_transports/default.py", line 30, in <module>
2023-04-09 14:48:39     import httpcore
2023-04-09 14:48:39   File "/usr/local/lib/python3.7/site-packages/httpcore/__init__.py", line 1, in <module>
2023-04-09 14:48:39     from ._api import request, stream
2023-04-09 14:48:39   File "/usr/local/lib/python3.7/site-packages/httpcore/_api.py", line 5, in <module>
2023-04-09 14:48:39     from ._sync.connection_pool import ConnectionPool
2023-04-09 14:48:39   File "/usr/local/lib/python3.7/site-packages/httpcore/_sync/__init__.py", line 1, in <module>
2023-04-09 14:48:39     from .connection import HTTPConnection
2023-04-09 14:48:39   File "/usr/local/lib/python3.7/site-packages/httpcore/_sync/connection.py", line 13, in <module>
2023-04-09 14:48:39     from .http11 import HTTP11Connection
2023-04-09 14:48:39   File "/usr/local/lib/python3.7/site-packages/httpcore/_sync/http11.py", line 44, in <module>
2023-04-09 14:48:39     class HTTP11Connection(ConnectionInterface):
2023-04-09 14:48:39   File "/usr/local/lib/python3.7/site-packages/httpcore/_sync/http11.py", line 140, in HTTP11Connection
2023-04-09 14:48:39     self, event: h11.Event, timeout: Optional[float] = None
2023-04-09 14:48:39 AttributeError: module 'h11' has no attribute 'Event'
```

**Comment by Homanism** [comment]
Did you update Vue version to the Vue 3?

**Comment by bashtian-fr** [comment]
> Did you update Vue version to the Vue 3?

it does not look like it:
https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/491/files#diff-8e05a756917525deabbc34b1a252d87191abf4dcf7fbb87497ea5147f4db6879R17

**Comment by tiangolo** [comment]
Thanks @da-maltsev! :coffee: 

This was refactored in a few other PRs, with some gradual upgrades, etc. So I'll close this one, but thanks for all the effort! :cake:

**Pull request closed without merging**
