### PR TITLE
Fix KeyError in crud_user.py and add test

### PR DESCRIPTION
**Pull request by michaeltoohig**

### CODE REVIEW

**Comment by Hultner** [comment]
I've had this problem as well and fixed it in pretty much the same way, reported here #285

**Comment by twcurrie** [comment]
Similar: https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/245

**Comment by ewae121** [comment]
Same for me

**Comment by tiangolo** [comment]
Thanks! This was handled in another PR, so I'll pass on this one. But thanks for the effort! :rocket:

**Pull request closed without merging**
