### PR TITLE
Update backend.dockerfile

### PR DESCRIPTION
**Pull request by sanggusti**
Update the outdated poetry installation link in backend dockerfile

### CODE REVIEW

**Review by ahmmkh — APPROVED** [review]

**Review by thoth2357 — APPROVED** [review]

**Review by EverStarck — APPROVED** [review]
LGTM!

**Review by oxfn — APPROVED** [review]

**Comment by Luan-vP** [comment]
Bump!

**Comment by tiangolo** [comment]
Thank you @sanggusti! This was handled in https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/480, so I'll now close this one.

But thanks for the effort! ☕

**Comment by sanggusti** [comment]
Sad, but at least @tiangolo replying on my pull request!! Could put this on my cv now 🥳🥳🥳

**Pull request closed without merging**
